# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "XuzhaoLi"
repo_name: "ro-arxiv-daily"
show_authors: True
show_links: True
max_results: 20

publish_readme: True
publish_gitpage: True

# file paths
json_readme_path: './docs/ro-arxiv-daily.json'
json_gitpage_path: './docs/ro-arxiv-daily-web.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'

# keywords to search
keywords:
    "Path Planning":
        filters: ["Minimum Control", "Route Planning", "Dynamic Programming", "Navigation", "Route Optimization", "Map Matching"]
    "Large Language Model":
        filters: ["LLM", "Language Model","Transformer", "BERT", "GPT", "Pre-training", "Fine-tuning", "Visual Language", "Prompt Learning", "Foundation Model"]
    "Autonomous Driving":
        filters: ["Autonomous Driving", "Planning", "Perception", "Decision Making", "Forecasting"]